
CREATE CACHED TABLE PUBLIC.PARKING_LOT(
    ID BIGINT NOT NULL,
    CAPACITY INTEGER NOT NULL CHECK (CAPACITY >= 0),
    LOCATION VARCHAR(255),
    NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.PARKING_LOT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.PARKING_LOT ADD CONSTRAINT PUBLIC.UK_2W49WOQIS4X25GEI7VNRE7X1I UNIQUE(NAME);
