CREATE CACHED TABLE PUBLIC.PARKING_ORDER(
    ID BIGINT NOT NULL,
    CARID VARCHAR(255),
    ENTER_TIME TIMESTAMP,
    EXIT_TIME TIMESTAMP,
    IS_OPEN BOOLEAN NOT NULL,
    NAME VARCHAR(255),
    PARKID BIGINT
);
ALTER TABLE PUBLIC.PARKING_ORDER ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PARKING_ORDER ADD CONSTRAINT PUBLIC.FKSUI5FYMLJLLMCGXALLNGHI8QQ FOREIGN KEY(PARKID) REFERENCES PUBLIC.PARKING_LOT(ID) NOCHECK;